[build]
  command = "npm install && npm run build"
  publish = ".next"
  functions = ".next/functions"

[build.environment]
  NPM_FLAGS = "--version=10.2.4"
  NODE_VERSION = "20.11.1"
  NODE_OPTIONS = "--max_old_space_size=4096"
  NPM_CONFIG_INCLUDE_DEV = "true"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000

[context.production.environment]
  NODE_ENV = "production"
