[build]
  command = "npm install && npm run build"
  publish = ".next/standalone"
  functions = ".next/functions"

[build.environment]
  NODE_VERSION = "20.11.1"
  NPM_VERSION = "10.2.4"
  NODE_OPTIONS = "--max_old_space_size=4096"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000

[context.production.environment]
  NODE_ENV = "production"
